ALTER TABLE concerts ADD COLUMN IF NOT EXISTS time TEXT;
ALTER TABLE concerts ADD COLUMN IF NOT EXISTS venue TEXT;
ALTER TABLE concerts ADD COLUMN IF NOT EXISTS price TEXT;
ALTER TABLE concerts ADD COLUMN IF NOT EXISTS available_seats INTEGER DEFAULT 0;
ALTER TABLE concerts ADD COLUMN IF NOT EXISTS ticket_url TEXT;