/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PreCheckoutRouteImport } from './routes/pre-checkout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as CancelRouteImport } from './routes/cancel'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'

const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PreCheckoutRoute = PreCheckoutRouteImport.update({
  id: '/pre-checkout',
  path: '/pre-checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const CancelRoute = CancelRouteImport.update({
  id: '/cancel',
  path: '/cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cancel': typeof CancelRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/pre-checkout': typeof PreCheckoutRoute
  '/privacy': typeof PrivacyRoute
  '/profil': typeof ProfilRoute
  '/register': typeof RegisterRoute
  '/success': typeof SuccessRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cancel': typeof CancelRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/pre-checkout': typeof PreCheckoutRoute
  '/privacy': typeof PrivacyRoute
  '/profil': typeof ProfilRoute
  '/register': typeof RegisterRoute
  '/success': typeof SuccessRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cancel': typeof CancelRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/pre-checkout': typeof PreCheckoutRoute
  '/privacy': typeof PrivacyRoute
  '/profil': typeof ProfilRoute
  '/register': typeof RegisterRoute
  '/success': typeof SuccessRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cancel'
    | '/legal'
    | '/login'
    | '/pre-checkout'
    | '/privacy'
    | '/profil'
    | '/register'
    | '/success'
    | '/demo/tanstack-query'
    | '/admin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cancel'
    | '/legal'
    | '/login'
    | '/pre-checkout'
    | '/privacy'
    | '/profil'
    | '/register'
    | '/success'
    | '/demo/tanstack-query'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/cancel'
    | '/legal'
    | '/login'
    | '/pre-checkout'
    | '/privacy'
    | '/profil'
    | '/register'
    | '/success'
    | '/demo/tanstack-query'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CancelRoute: typeof CancelRoute
  LegalRoute: typeof LegalRoute
  LoginRoute: typeof LoginRoute
  PreCheckoutRoute: typeof PreCheckoutRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfilRoute: typeof ProfilRoute
  RegisterRoute: typeof RegisterRoute
  SuccessRoute: typeof SuccessRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pre-checkout': {
      id: '/pre-checkout'
      path: '/pre-checkout'
      fullPath: '/pre-checkout'
      preLoaderRoute: typeof PreCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cancel': {
      id: '/cancel'
      path: '/cancel'
      fullPath: '/cancel'
      preLoaderRoute: typeof CancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CancelRoute: CancelRoute,
  LegalRoute: LegalRoute,
  LoginRoute: LoginRoute,
  PreCheckoutRoute: PreCheckoutRoute,
  PrivacyRoute: PrivacyRoute,
  ProfilRoute: ProfilRoute,
  RegisterRoute: RegisterRoute,
  SuccessRoute: SuccessRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
